name: Test testutils

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout Release-Specs
      uses: actions/checkout@v2
      with:
        path: Release-Specs
    - name: Checkout RIOT
      uses: actions/checkout@v2
      with:
        repository: RIOT-OS/RIOT
        fetch-depth: 1
        path: RIOT
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      env:
        RIOTBASE: ${{ github.workspace }}/RIOT
      run: |
        pyenv="py$(echo "${{ matrix.python-version }}" | tr -d .)"
        cd Release-Specs
        tox -e "test,${pyenv},flake8,pylint" -- --doctest-modules --self-test \
            --cov=testutils --cov-report term-missing \
            --cov-config=testutils/.coveragerc \
            --cov-fail-under=95
    - name: Check code format with black
      if: matrix.python-version == '3.10'
      run: |
        cd Release-Specs
        tox -e black
